2023-03-13 14:15:19,695 ERROR: Exception on /auth/login [GET] [in C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Nick\Documents\Praxisarbeit\app\auth\routes.py", line 24, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\base.html", line 50, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\auth\login.html", line 12, in block 'app_content'
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2023-03-13 14:15:22,120 ERROR: Exception on /auth/login [GET] [in C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Nick\Documents\Praxisarbeit\app\auth\routes.py", line 24, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\base.html", line 50, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\Nick\Documents\Praxisarbeit\app\templates\auth\login.html", line 12, in block 'app_content'
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2023-03-13 14:19:41,427 INFO: Certificates startup [in C:\Users\Nick\Documents\Praxisarbeit\app\__init__.py:48]
