2023-03-13 17:00:26,641 ERROR: Exception on /api/download/csr/mnfsdjnfsdjfsd.post.ch [GET] [in C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Nick\Documents\Praxisarbeit\praxisarbeit\lib\site-packages\flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "C:\Users\Nick\Documents\Praxisarbeit\app\api\certificates.py", line 27, in get_certificate_csr
    certificate = Certificate.query.filter_by(cn=cn, user_id=current_user.id).first_or_404()
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
2023-03-14 10:17:31,360 INFO: Certificates startup [in C:\Users\Nick\Documents\Praxisarbeit\app\__init__.py:51]
